# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tar_palantir/REPOS/url_shorterner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tar_palantir/REPOS/url_shorterner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tar_palantir/REPOS/url_shorterner/CMakeFiles /home/tar_palantir/REPOS/url_shorterner//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tar_palantir/REPOS/url_shorterner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named httplib

# Build rule for target.
httplib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 httplib
.PHONY : httplib

# fast build rule for target.
httplib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httplib.dir/build.make CMakeFiles/httplib.dir/build
.PHONY : httplib/fast

#=============================================================================
# Target rules for targets named url_shorterner

# Build rule for target.
url_shorterner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 url_shorterner
.PHONY : url_shorterner

# fast build rule for target.
url_shorterner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/url_shorterner.dir/build.make CMakeFiles/url_shorterner.dir/build
.PHONY : url_shorterner/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f lib/spdlog/CMakeFiles/spdlog.dir/build.make lib/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

lib/httplib/httplib.o: lib/httplib/httplib.cc.o
.PHONY : lib/httplib/httplib.o

# target to build an object file
lib/httplib/httplib.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httplib.dir/build.make CMakeFiles/httplib.dir/lib/httplib/httplib.cc.o
.PHONY : lib/httplib/httplib.cc.o

lib/httplib/httplib.i: lib/httplib/httplib.cc.i
.PHONY : lib/httplib/httplib.i

# target to preprocess a source file
lib/httplib/httplib.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httplib.dir/build.make CMakeFiles/httplib.dir/lib/httplib/httplib.cc.i
.PHONY : lib/httplib/httplib.cc.i

lib/httplib/httplib.s: lib/httplib/httplib.cc.s
.PHONY : lib/httplib/httplib.s

# target to generate assembly for a file
lib/httplib/httplib.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/httplib.dir/build.make CMakeFiles/httplib.dir/lib/httplib/httplib.cc.s
.PHONY : lib/httplib/httplib.cc.s

src/url_shorterner.o: src/url_shorterner.cpp.o
.PHONY : src/url_shorterner.o

# target to build an object file
src/url_shorterner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/url_shorterner.dir/build.make CMakeFiles/url_shorterner.dir/src/url_shorterner.cpp.o
.PHONY : src/url_shorterner.cpp.o

src/url_shorterner.i: src/url_shorterner.cpp.i
.PHONY : src/url_shorterner.i

# target to preprocess a source file
src/url_shorterner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/url_shorterner.dir/build.make CMakeFiles/url_shorterner.dir/src/url_shorterner.cpp.i
.PHONY : src/url_shorterner.cpp.i

src/url_shorterner.s: src/url_shorterner.cpp.s
.PHONY : src/url_shorterner.s

# target to generate assembly for a file
src/url_shorterner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/url_shorterner.dir/build.make CMakeFiles/url_shorterner.dir/src/url_shorterner.cpp.s
.PHONY : src/url_shorterner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... httplib"
	@echo "... spdlog"
	@echo "... url_shorterner"
	@echo "... lib/httplib/httplib.o"
	@echo "... lib/httplib/httplib.i"
	@echo "... lib/httplib/httplib.s"
	@echo "... src/url_shorterner.o"
	@echo "... src/url_shorterner.i"
	@echo "... src/url_shorterner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

